import { Link } from "@tanstack/react-router";
import { ArrowRight,CheckCircle2,Download,MessageSquareText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EnquiryForm } from "@/components/enquiry";
import { describeType,pillarList,type Pillar,type SubCategory } from "@/lib/site-data";
import powerImg from "@/assets/power-transmission.jpg";import automationImg from "@/assets/automation.jpg";import adhesivesImg from "@/assets/adhesives.jpg";
const images={power:powerImg,automation:automationImg,adhesives:adhesivesImg};
export function Breadcrumbs({items}:{items:{label:string;to:string}[]}){return <nav aria-label="Breadcrumb" className="site-container py-4 text-xs text-muted-foreground"><ol className="flex flex-wrap gap-2"><li><Link to="/">Home</Link></li>{items.map(i=><li key={i.to} className="before:mr-2 before:content-['/']"><a href={i.to}>{i.label}</a></li>)}</ol></nav>}
export function PageHero({kicker,title,description,image,accent="brand"}:{kicker:string;title:string;description:string;image?:string;accent?:string}){return <section className={`page-hero pattern-${accent}`}><div className="absolute inset-0 bg-foreground/75"/>{image&&<img src={image} alt="Industrial machinery and components" width={1408} height={912} className="absolute inset-0 -z-10 size-full object-cover"/>}<div className="site-container relative py-20 text-background md:py-28"><p className="eyebrow text-primary-soft">{kicker}</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-background/80">{description}</p></div></section>}
export function SectionHeading({eyebrow,title,text}:{eyebrow?:string;title:string;text?:string}){return <div className="mb-10 max-w-3xl">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2 className="section-title mt-3">{title}</h2>{text&&<p className="mt-4 text-lg leading-8 text-muted-foreground">{text}</p>}</div>}
export function PillarCards(){return <div className="grid gap-5 lg:grid-cols-3">{pillarList.map(p=><article key={p.key} className={`pillar-card pillar-${p.key}`}><img src={images[p.image]} alt={`${p.name} industrial equipment`} width={1408} height={912} loading="lazy"/><div className="p-6"><span className="eyebrow">Division 0{pillarList.indexOf(p)+1}</span><h3 className="mt-2 text-2xl font-black">{p.name}</h3><p className="mt-3 leading-7 text-muted-foreground">{p.description}</p><Button asChild variant="link" className="mt-3 px-0"><Link to={`/${p.key}` as "/power-transmission"|"/automation"|"/adhesives"}>Explore range <ArrowRight/></Link></Button></div></article>)}</div>}
export function BrandStrip({brands}:{brands:string[]}){return <div className="brand-strip" aria-label="Available brands"><div className="brand-track">{[...brands,...brands].map((b,i)=><div className="brand-chip" key={`${b}-${i}`}>{b}</div>)}</div></div>}
export function CategoryGrid({pillar}:{pillar:Pillar}){return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{pillar.subcategories.map((s,i)=><article className="category-card" key={s.slug}><span className="text-xs font-black text-category">0{i+1}</span><h3 className="mt-5 text-xl font-black">{s.name}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-muted-foreground">{s.short}</p><div className="mt-6 flex flex-wrap gap-2"><Button asChild size="sm"><Link to={`/${pillar.key}/$slug` as "/power-transmission/$slug"} params={{slug:s.slug}}>View range <ArrowRight/></Link></Button><Button asChild variant="outline" size="sm"><a href={`/${pillar.key}/${s.slug}#enquire`}>Quick enquiry</a></Button></div></article>)}</div>}
export function BrochureGrid({brands}:{brands:string[]}){return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{brands.slice(0,8).map(b=><article key={b} className="border border-border bg-background p-5"><Download className="text-primary"/><h3 className="mt-5 font-black">Brochure: {b}</h3><p className="mt-2 text-xs text-muted-foreground">PDF will be added after digitisation.</p><Button disabled variant="outline" size="sm" className="mt-5">Download PDF</Button></article>)}</div>}
export function ProductTypes({pillar,sub,onQuote,onView}:{pillar:Pillar;sub:SubCategory;onQuote?:(name:string)=>void;onView?:(name:string)=>void}){return <div className="grid gap-4 md:grid-cols-2">{sub.types.map((t,i)=><article key={t} className="product-type"><div className="flex items-start justify-between gap-4"><span className="grid size-9 shrink-0 place-items-center bg-category text-sm font-black text-category-foreground">{String(i+1).padStart(2,"0")}</span><CheckCircle2 className="text-category"/></div><h3 className="mt-6 text-xl font-black">{t}</h3><p className="mt-3 leading-7 text-muted-foreground">{describeType(t)}</p>{onView?<Button className="mt-5" onClick={()=>onView(t)}>View range <ArrowRight/></Button>:onQuote&&<Button variant="outline" className="mt-5" onClick={()=>onQuote(t)}><MessageSquareText/>Request quote</Button>}</article>)}</div>}
export function EnquiryBand({title,category,requirement}:{title:string;category:string;requirement?:string}){return <section id="enquire" className="pattern-shared bg-muted py-16"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Technical enquiry</p><h2 className="section-title mt-3">{title}</h2><p className="mt-5 leading-7 text-muted-foreground">Share a part number, size, brand, drawing or application. Our team will help identify the right option.</p></div><div className="border border-border bg-background p-5 shadow-sm md:p-8"><EnquiryForm seed={requirement?{category,requirement}:{category}} compact/></div></div></section>}
export {images};
