import { useEffect,useState } from "react";
import { Link,useRouterState } from "@tanstack/react-router";
import { Menu,Search,X,MessageCircle,ArrowUp,ChevronDown,MapPin,Phone,Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Brand } from "@/components/brand";
import { EnquiryDialog,type EnquirySeed,WA_PHONE } from "@/components/enquiry";
import { navItems,pillarList,searchItems } from "@/lib/site-data";
import logo from "@/assets/rb-logo.jpg.asset.json";
export function SiteShell({children}:{children:React.ReactNode}){const path=useRouterState({select:s=>s.location.pathname});const [menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(""),[enquiry,setEnquiry]=useState(false),[seed,setSeed]=useState<EnquirySeed>({}),[top,setTop]=useState(false),[preload,setPreload]=useState(false);
useEffect(()=>{setMenu(false);setSearch(false);window.scrollTo(0,0)},[path]);useEffect(()=>{const seen=sessionStorage.getItem("rb-intro");if(seen)return;setPreload(true);sessionStorage.setItem("rb-intro","1");const timer=setTimeout(()=>setPreload(false),2400);return()=>clearTimeout(timer)},[]);useEffect(()=>{const f=()=>setTop(window.scrollY>700);addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);
const context=path.split("/").filter(Boolean).map(x=>x.replaceAll("-"," ")).join(" / ");const matches=query.trim()?searchItems.filter(x=>`${x.name} ${x.keywords}`.includes(query.toLowerCase())).slice(0,8):[];const open=(s:EnquirySeed={})=>{setSeed(s);setEnquiry(true)};
return <><div className={`preloader ${preload?"is-visible":""}`} aria-hidden={!preload}><img src={logo.url} alt=""/><strong>RB International</strong><span>Belting & Automation</span></div><header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur"><div className="bg-foreground py-2 text-background"><div className="site-container flex items-center justify-between gap-4 text-xs"><span className="truncate">Serving Indian industry since 2003</span><div className="flex shrink-0 gap-4"><a href="tel:+918788195839" className="hover:text-primary-soft">+91 87881 95839</a><span className="hidden sm:inline">PAN India + Export</span></div></div></div><div className="site-container grid h-20 grid-cols-[minmax(0,1fr)_auto] items-center gap-3 xl:grid-cols-[auto_minmax(0,1fr)_auto]"><Link to="/" aria-label="RB International home"><Brand compact/></Link><nav className="hidden min-w-0 items-center justify-center gap-1 xl:flex">{navItems.map(n=><div key={n.to} className="group relative"> <Link to={n.to} className="inline-flex h-11 items-center gap-1 px-2 text-xs font-bold uppercase text-foreground hover:text-primary" activeProps={{className:"text-primary"}}>{n.label}{pillarList.some(p=>`/${p.key}`===n.to)&&<ChevronDown className="size-3"/>}</Link>{pillarList.find(p=>`/${p.key}`===n.to)&&<div className="invisible absolute left-0 top-full w-72 translate-y-2 border border-border bg-background p-2 opacity-0 shadow-xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100">{pillarList.find(p=>`/${p.key}`===n.to)?.subcategories.map(s=><a key={s.slug} href={`${n.to}/${s.slug}`} className="block border-b border-border px-3 py-2 text-sm font-medium last:border-0 hover:bg-muted hover:text-primary">{s.name}</a>)}</div>}</div>)}</nav><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Search products" onClick={()=>setSearch(true)}><Search/></Button><Button variant="ghost" size="icon" className="xl:hidden" aria-label="Open menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="max-h-[calc(100vh-7rem)] overflow-auto border-t border-border bg-background px-4 py-3 xl:hidden">{navItems.map(n=><Link key={n.to} to={n.to} className="block border-b border-border py-3 font-bold">{n.label}</Link>)}</nav>}</header>
{search&&<div className="fixed inset-0 z-50 bg-foreground/80 p-4 backdrop-blur-sm" onClick={()=>setSearch(false)}><div className="mx-auto mt-[10vh] max-w-2xl bg-background p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3"><Search className="shrink-0 text-primary"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value.slice(0,100))} placeholder="Search product, brand or part type" className="h-14 min-w-0 flex-1 bg-transparent text-lg outline-none"/><Button variant="ghost" size="icon" onClick={()=>setSearch(false)}><X/></Button></div><div className="border-t border-border pt-2">{matches.map((m,i)=><a href={m.to} key={`${m.name}-${i}`} className="flex justify-between border-b border-border px-2 py-3 text-sm font-semibold hover:bg-muted"><span>{m.name}</span><span className="text-primary">View range</span></a>)}{query&&matches.length===0&&<Button variant="ghost" className="h-auto w-full justify-start whitespace-normal py-4 text-left" onClick={()=>{setSearch(false);open({requirement:query})}}>No exact match? Submit an enquiry for “{query}”</Button>}</div></div></div>}
<main>{children}</main><Footer/>{top&&<button className="quick-enquiry" onClick={()=>open({requirement:context?`I am looking for ${context}`:""})}>Can't find what you need?</button>}<a className="whatsapp-float" href={`https://wa.me/${WA_PHONE}?text=${encodeURIComponent(`Hi, I'm reaching out from your website. I'm looking for: ${context}`)}`} aria-label="Message RB International on WhatsApp"><MessageCircle/></a>{top&&<Button size="icon" variant="outline" className="fixed bottom-24 right-5 z-30 bg-background shadow-lg" onClick={()=>scrollTo({top:0,behavior:"smooth"})} aria-label="Scroll to top"><ArrowUp/></Button>}<EnquiryDialog open={enquiry} onOpenChange={setEnquiry} seed={seed}/></>}
function Footer(){return <footer className="bg-foreground text-background"><div className="site-container grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-4"><div><Brand/><p className="mt-5 text-sm leading-6 text-background/70">A single source for power transmission, motion control and industrial adhesive requirements since 2003.</p><span className="mt-5 inline-block border border-background/20 px-3 py-2 text-xs font-bold">SINCE 2003</span></div><div><h2 className="footer-title">Product divisions</h2>{pillarList.map(p=><a key={p.key} href={`/${p.key}`} className="footer-link">{p.name}</a>)}</div><div><h2 className="footer-title">Company</h2>{navItems.filter(x=>!["/","/power-transmission","/automation","/adhesives"].includes(x.to)).map(n=><a key={n.to} href={n.to} className="footer-link">{n.label}</a>)}</div><div><h2 className="footer-title">Contact Pune</h2><p className="footer-contact"><MapPin/>Shop No 5, Kamath Complex, Telco Road, Landewadi, Bhosari Industrial Estate, Pune 411026</p><a className="footer-contact" href="tel:+918788195839"><Phone/>+91 87881 95839</a><a className="footer-contact" href="mailto:response@rbibelting.in"><Mail/>response@rbibelting.in</a></div></div><div className="border-t border-background/10 py-5 text-center text-xs text-background/60">© 2026 RB International Belting & Automation. All rights reserved.</div></footer>}
