/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdhesivesRouteImport } from './routes/adhesives'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as PowerTransmissionRouteImport } from './routes/power-transmission'
import { Route as AdhesivesSlugRouteImport } from './routes/adhesives.$slug'
import { Route as AutomationSlugRouteImport } from './routes/automation.$slug'
import { Route as PowerTransmissionSlugRouteImport } from './routes/power-transmission.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhesivesRoute = AdhesivesRouteImport.update({
  id: '/adhesives',
  path: '/adhesives',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerTransmissionRoute = PowerTransmissionRouteImport.update({
  id: '/power-transmission',
  path: '/power-transmission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhesivesSlugRoute = AdhesivesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdhesivesRoute,
} as any)
const AutomationSlugRoute = AutomationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AutomationRoute,
} as any)
const PowerTransmissionSlugRoute = PowerTransmissionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PowerTransmissionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adhesives': typeof AdhesivesRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/power-transmission': typeof PowerTransmissionRouteWithChildren
  '/adhesives/$slug': typeof AdhesivesSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/power-transmission/$slug': typeof PowerTransmissionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adhesives': typeof AdhesivesRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/power-transmission': typeof PowerTransmissionRouteWithChildren
  '/adhesives/$slug': typeof AdhesivesSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/power-transmission/$slug': typeof PowerTransmissionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adhesives': typeof AdhesivesRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/power-transmission': typeof PowerTransmissionRouteWithChildren
  '/adhesives/$slug': typeof AdhesivesSlugRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/power-transmission/$slug': typeof PowerTransmissionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adhesives'
    | '/automation'
    | '/brands'
    | '/contact'
    | '/franchise'
    | '/power-transmission'
    | '/adhesives/$slug'
    | '/automation/$slug'
    | '/power-transmission/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adhesives'
    | '/automation'
    | '/brands'
    | '/contact'
    | '/franchise'
    | '/power-transmission'
    | '/adhesives/$slug'
    | '/automation/$slug'
    | '/power-transmission/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adhesives'
    | '/automation'
    | '/brands'
    | '/contact'
    | '/franchise'
    | '/power-transmission'
    | '/adhesives/$slug'
    | '/automation/$slug'
    | '/power-transmission/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdhesivesRoute: typeof AdhesivesRouteWithChildren
  AutomationRoute: typeof AutomationRouteWithChildren
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  PowerTransmissionRoute: typeof PowerTransmissionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhesives': {
      id: '/adhesives'
      path: '/adhesives'
      fullPath: '/adhesives'
      preLoaderRoute: typeof AdhesivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-transmission': {
      id: '/power-transmission'
      path: '/power-transmission'
      fullPath: '/power-transmission'
      preLoaderRoute: typeof PowerTransmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhesives/$slug': {
      id: '/adhesives/$slug'
      path: '/$slug'
      fullPath: '/adhesives/$slug'
      preLoaderRoute: typeof AdhesivesSlugRouteImport
      parentRoute: typeof AdhesivesRoute
    }
    '/automation/$slug': {
      id: '/automation/$slug'
      path: '/$slug'
      fullPath: '/automation/$slug'
      preLoaderRoute: typeof AutomationSlugRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/power-transmission/$slug': {
      id: '/power-transmission/$slug'
      path: '/$slug'
      fullPath: '/power-transmission/$slug'
      preLoaderRoute: typeof PowerTransmissionSlugRouteImport
      parentRoute: typeof PowerTransmissionRoute
    }
  }
}

interface AdhesivesRouteChildren {
  AdhesivesSlugRoute: typeof AdhesivesSlugRoute
}

const AdhesivesRouteChildren: AdhesivesRouteChildren = {
  AdhesivesSlugRoute: AdhesivesSlugRoute,
}

const AdhesivesRouteWithChildren = AdhesivesRoute._addFileChildren(
  AdhesivesRouteChildren,
)

interface AutomationRouteChildren {
  AutomationSlugRoute: typeof AutomationSlugRoute
}

const AutomationRouteChildren: AutomationRouteChildren = {
  AutomationSlugRoute: AutomationSlugRoute,
}

const AutomationRouteWithChildren = AutomationRoute._addFileChildren(
  AutomationRouteChildren,
)

interface PowerTransmissionRouteChildren {
  PowerTransmissionSlugRoute: typeof PowerTransmissionSlugRoute
}

const PowerTransmissionRouteChildren: PowerTransmissionRouteChildren = {
  PowerTransmissionSlugRoute: PowerTransmissionSlugRoute,
}

const PowerTransmissionRouteWithChildren =
  PowerTransmissionRoute._addFileChildren(PowerTransmissionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdhesivesRoute: AdhesivesRouteWithChildren,
  AutomationRoute: AutomationRouteWithChildren,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  PowerTransmissionRoute: PowerTransmissionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
